language: cpp
sudo: required
dist: trusty
compiler:
    - clang
    - gcc
before_install:
    - echo $LANG
    - sudo apt-get -qq install software-properties-common
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -qq update
    - sudo apt-get -qq install build-essential
    - pip install --user cpp-coveralls
    - sudo apt-get -qq install valgrind curl libicu-dev libhttp-parser-dev openssl libboost-all-dev lcov
    - $CXX --version
    - wget -q -O libuv-v1.8.0.tar.gz http://dist.libuv.org/dist/v1.8.0/libuv-v1.8.0.tar.gz
    - tar -xzf libuv-v1.8.0.tar.gz
    - cd libuv-v1.8.0/
    - sh autogen.sh && ./configure && make --quiet && sudo make install --quiet
    - cd ../
before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
script: make -j2 && make test
after_success:
    - coveralls --exclude test --gcov-options '\-lp'
branches:
    only:
        - master
        - develop
