language: cpp
sudo: required
dist: trusty
compiler:
    - clang
    - gcc
before_install:
    - echo $LANG
    - sudo apt-get -qq install software-properties-common
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -qq update
    - sudo apt-get -qq install build-essential
    - pip install --user cpp-coveralls
    - sudo apt-get -qq install valgrind curl libicu-dev libhttp-parser-dev openssl libboost-all-dev lcov libuv-dev
    - $CXX --version
before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
script: make -j2 && make test
after_success:
    - coveralls --exclude test --gcov-options '\-lp'
branches:
    only:
        - master
        - develop
