language: cpp
sudo: false
compiler:
    - clang
    - gcc
before_install:
    - echo $LANG
    - apt-get -qq install python-software-properties
    - add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - apt-get -qq update
    - apt-get -qq install build-essential gcc-4.8 g++-4.8
    - pip install --user cpp-coveralls
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
    - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
    - apt-get -qq install valgrind curl libicu-dev libhttp-parser-dev openssl
    - $CXX --version
before_script:
    - mkdir build
    - cd build
    - cmake ..
script: make && make test
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
branches:
    only:
        - master
        - develop
